# Generated by Django 2.2 on 2019-04-23 22:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190423_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
