# Generated by Django 2.2 on 2019-04-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190423_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
