# Generated by Django 2.2 on 2019-04-23 23:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190423_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Director', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden en que se muestran')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('anexo', models.CharField(blank=True, help_text='Regente de Cultura Técnica T.T.', max_length=150, null=True)),
                ('foto', models.ImageField(default='institucional/perfil/no-img.jpg', upload_to='institucional/perfil')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='sitio web')),
                ('info', ckeditor.fields.RichTextField(blank=True, help_text='Mas información', null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Cargo')),
            ],
        ),
    ]
