# Generated by Django 2.2 on 2019-04-23 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, help_text='Ej: DNI / CI, LE , LC, Pasaporte', max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Femenino', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_apellido', models.CharField(blank=True, help_text='campo no obligatorio', max_length=100, null=True, verbose_name='segundo apellido')),
                ('segundo_nombre', models.CharField(blank=True, help_text='campo no obligatorio', max_length=50, null=True, verbose_name='segundo nombre')),
                ('numero_documento', models.CharField(blank=True, help_text='Ej: 38-090879-9', max_length=15, null=True, verbose_name='numero de documento / pasaporte')),
                ('numero_empleado', models.CharField(blank=True, max_length=30, null=True, verbose_name='numero empleado')),
                ('legajo_cpe', models.CharField(blank=True, help_text='CPE: Consejo provincial de educación', max_length=50, null=True, verbose_name='legajo CPE')),
                ('observación', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('pais_nacimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuario.Pais')),
                ('sexo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Sexo')),
                ('tipo_documento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuario.Documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
