# Generated by Django 2.2 on 2019-04-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name': 'sexo', 'verbose_name_plural': 'sexos'},
        ),
    ]
