# Generated by Django 2.2 on 2019-04-23 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libreta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100, verbose_name='calle / cuadra')),
                ('telefono_contacto', models.CharField(max_length=50, verbose_name='telefono de contacto')),
                ('observación', models.TextField(blank=True, null=True)),
                ('localidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agenda.Localidad')),
                ('provincia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agenda.Provincia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
