# Generated by Django 2.2 on 2019-04-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libreta',
            options={'verbose_name': 'libreta', 'verbose_name_plural': 'libretas'},
        ),
    ]
