# Generated by Django 2.2 on 2019-04-24 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190423_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libreta',
            name='observación',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
